[keyboard.names]
fill_in_data = "Заполнить данные 🧑‍💻"
start_program = "Запустить программу 🏃"
view_completed_data = "Посмотреть заполненные данные 🗾"


[commands.general.messages]
start_bot = "Привет! Запуск практической работы №7 по многоагентному моделированию."
task_completed = "Ура! Вы завершили задачу!"

[commands.datawriter.messages]
number_people_in_population = "Введите число популяции людей:"
percentage_of_consumers_per_day = "Отлично!\nТеперь введите процент потребителей в день:"
product_storage_time_in_days = "И последний параметр!\nВведите срок сохранности продукта в днях."

[commands.error.messages]
command_not_found = "Введенная комманда не найдена. Пожалуйста повторите ввод снова!"
invalid_value = "Вы ввели не верное значение! Повторите еще раз)"

[commands.dataoutput.messages]
correct_output = "На данный момент вы ввели следующие данные:\n1) Число популяции людей: {};\n2) Процент потребителей в ден: {};\n3) Срок хранения товара: {};"
no_data_available = "Вы не ввели никакие данные :("

