"""Update links user and datawriter

Revision ID: 6501bfbe200b
Revises: 97dfb7b27e3f
Create Date: 2022-05-18 19:02:26.710787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6501bfbe200b'
down_revision = '97dfb7b27e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_datawriters_user_id_users', 'datawriters', type_='foreignkey')
    op.create_foreign_key(op.f('fk_datawriters_user_id_users'), 'datawriters', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_datawriters_user_id_users'), 'datawriters', type_='foreignkey')
    op.create_foreign_key('fk_datawriters_user_id_users', 'datawriters', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
