"""Create a new table

Revision ID: 97dfb7b27e3f
Revises: 1e0f0f8c63eb
Create Date: 2022-05-18 16:42:58.326747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dfb7b27e3f'
down_revision = '1e0f0f8c63eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('user_id', name=op.f('uq_users_user_id'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('datawriters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('people_in_population', sa.Integer(), nullable=False),
    sa.Column('percentage_of_consumers', sa.Integer(), nullable=False),
    sa.Column('product_storage_time_in_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_datawriters_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datawriters'))
    )
    op.create_index(op.f('ix_datawriters_id'), 'datawriters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datawriters_id'), table_name='datawriters')
    op.drop_table('datawriters')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
